# Generated by Django 5.0.4 on 2024-05-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgod', '0004_pdf_is_copied'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
